#!/bin/bash
# Load FunctionLibs
. "/usr/local/bin/functions/colors"
. "/usr/local/bin/addPath"
. "/usr/local/bin/addFile"
. "/usr/local/bin/slashKill"
. "/usr/local/bin/catPath"
. "/usr/local/bin/fileCp"







